### ISSUE TITLE
Audio does not work client side.

### ISSUE THREAD

**Issue by Hayas19** [steven4547466/YoutubeBoombox#10]
Audio does not play on client side, within the bepin window it displays this error when booting the game. 
![Screenshot 2023-12-09 004840](https://github.com/steven4547466/YoutubeBoombox/assets/153361112/ff735fc9-0f31-4268-9726-95e52e0dcaf1)

This is on version 1.3.0.

**Comment by steven4547466** [comment]
Asset bundle loading is an LCAPI error, not related to audio not loading. I have been made aware of possible issues with 1.3.0 regarding audio playing and am investigating it now

**Comment by steven4547466** [comment]
Hey, I just released 1.3.1 which should fix the actual issue in here. Those logs are due to the LCAPI, and I can't do anything about them, but they mean nothing. But the actual issue should be fixed. Reopen if it isn't

**Comment by Hayas19** [comment]
It is fixed! Thank you for your hard work! I only brought up that LCAPI error because the previous version (1.2.2) did not show that error. They do not appear in 1.3.1. 
  
There is a bug I found with shortened "youtu.be" links throwing this error, 
![image](https://github.com/steven4547466/YoutubeBoombox/assets/153361112/8977d7ed-dc21-46ef-9881-bc6210e4dc31)
but regular links work.

And I don't know if it's appropriate to put here, but songs/videos that are 10mins or more will play the last played song.
