### ISSUE TITLE
Audo Files Not loading

### ISSUE THREAD

**Issue by DrPeep** [steven4547466/YoutubeBoombox#11]
I'm not to certain why this issue is occurring but did SS the logs so that maybe somebody could help me to understand the issue. We have mods installed using "r2modman" MM and the List of mods installed are as included.
-BepinExPack by BepinEx
-MoreCompany by notnotnotswipez
-Skinwalkers by RugbugRedfern
-MineMineMine by mattplays
-Mimics by x753
-LC_API
-More_Emotes by Sligili
-CommandHandler by steven4547466
-YoutubeBoombox by steven4547466
![log1](https://github.com/steven4547466/YoutubeBoombox/assets/153413941/e22b54f5-cc4a-4555-90e2-e6a07f9efb4b)
![log2](https://github.com/steven4547466/YoutubeBoombox/assets/153413941/b749922d-5661-45a6-bf51-f5e74d52a737)
![log3](https://github.com/steven4547466/YoutubeBoombox/assets/153413941/17952a4e-9a08-4d24-bc1a-89292f328c64)

**Comment by DrPeep** [comment]
I also forgot to mention that the only audio files we attempted to use were https://www.youtube.com/watch?v=5qm8PH4xAss
As it was the first song that came to mind and was attempted to be used.
And https://youtu.be/5qm8PH4xAss?si=iA4q2EePUhzW1MnQ
so I attempted both the watch and .be links

**Comment by steven4547466** [comment]
Dissonance is voice chat related so I don't think that's part of this issue the main issue is the red text at the top. It seems that it didn't properly download as an MP3. I have a potential solution for this in the next patch, which will probably come out sometime tonight.

**Comment by LiiftYourself** [comment]
Just commenting to say that I've also encountered this exact same issue. Unsure how significant this is, but I also use the skinwalkers mod!

**Comment by DrPeep** [comment]
> Dissonance is voice chat related so I don't think that's part of this issue the main issue is the red text at the top. It seems that it didn't properly download as an MP3. I have a potential solution for this in the next patch, which will probably come out sometime tonight.

Awesome and Gotcha will be looking forward to it!

**Comment by steven4547466** [comment]
I released 1.4.0, let me know if this reappears by reopening this issue!
