### ISSUE TITLE
How do I compile the repo?

### ISSUE THREAD

**Issue by InstSnipe** [steven4547466/YoutubeBoombox#14]
I tried following the end section of this tutorial:
https://www.youtube.com/watch?v=4Q7Zp5K2ywI 
but to no avail

(I saw that there's a v1.40 in the repo, so I could use the mod in the latest version)

**Comment by InstSnipe** [comment]
@steven4547466

**Comment by steven4547466** [comment]
You need to have [UnityNetcodeWeaver](https://github.com/EvaisaDev/UnityNetcodeWeaver) and to have a publicized game assembly. I use [this publicizer](https://github.com/iRebbok/APublicizer/releases). You'll need to edit the post build event to properly point to your location for netcode weaver

**Comment by steven4547466** [comment]
As of sometime yesterday, I switched the publicizer over to a nuget package, so that should no longer be required
