### ISSUE TITLE
[Suggestion]support music from additional websites

### ISSUE THREAD

**Issue by INSANEMODE** [steven4547466/YoutubeBoombox#15]
Could support for places like soundcloud be added, in the future? youtube-dlp supports it out of the box, but your mod can't handle them at the moment, since you explicitly expect youtube links.

https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md

**Comment by steven4547466** [comment]
Will look into this.

**Comment by steven4547466** [comment]
I did try this, but soundcloud's API requires authentication meaning I can't grab duration data or even download playlist/album song urls for downloading them one at a time. It would take a full rewrite to handle soundcloud playlists and albums, but nothing would allow me to get the duration data bar scraping the page, so unfortunately I will not be pursuing this at the moment.
