### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by Dracu0** [steven4547466/YoutubeBoombox#16]
No "press this button to use" on the UI, B does nothing and the there's no option to change the keybind in the keybind menu.

**Comment by Hydromistt** [comment]
> No "press this button to use" on the UI, B does nothing and the there's no option to change the keybind in the keybind menu.

How did you end up getting it to work? I'm having the same issue.

**Comment by Dracu0** [comment]
> > No "press this button to use" on the UI, B does nothing and the there's no option to change the keybind in the keybind menu.
> 
> How did you end up getting it to work? I'm having the same issue. 

Had to re-install BepinEx manually from its GitHub, mod managers have 5.4.21 Unnistall your BepinEx and download 5.4.22 from the latest releases tab. That worked for me, hope it works for you.
