### ISSUE TITLE
Using this mod makes some Antivirus detect it as malware

### ISSUE THREAD

**Issue by Dracu0** [steven4547466/YoutubeBoombox#19]
Some of my friends keep getting an error when using this mod because the antivirus detects it as malware when trying to fetch info from a link.

**Comment by steven4547466** [comment]
I can't do anything about false positives and I do **not** recommend turning off AV to play songs on a boombox in a game. If everyone in the game is trusted, maybe, but I still wouldn't recommend it. Even though I don't think any viruses are possible here.
