### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by DTM450** [steven4547466/YoutubeBoombox#2]
Can we get a short guide on how to use the mod?

**Comment by steven4547466** [comment]
I'll put a video in the readme.

**Comment by undinayable** [comment]
yes please

**Comment by steven4547466** [comment]
https://github.com/steven4547466/YoutubeBoombox/blob/master/README.md

I also put a small guide. One very important thing: make sure you're on version 1.0.3 or later as previous versions had some issues regarding the UI, sometimes not popping up at all.
