### ISSUE TITLE
[Suggestion] Use LC API command handler

### ISSUE THREAD

**Issue by thaddeuskkr** [steven4547466/YoutubeBoombox#20]
LC API has a command handler (since version 2.2.0).

Since this mod depends on both LC API and [LethalCompanyCommandHandler](https://github.com/steven4547466/LethalCompanyCommandHandler), there are conflicts if the prefix are the same (by default, they are) - which causes the `/bbv` command not to work.

This would reduce dependencies as well as simplify configurations.

**Comment by steven4547466** [comment]
Yeah I wrote the LCAPI command handler by copying my command handler code into it. Next update will fix this as I am switching it over.

**Comment by steven4547466** [comment]
Added in 1.5.0
