### ISSUE TITLE
3 issues

### ISSUE THREAD

**Issue by courtesy10** [steven4547466/YoutubeBoombox#5]
When copy and pasting the url you should make it so you dont crouch when you press control, its also not syncing up at the same time but that might because im using 1.1.3, also it slows down in the middle of a song even though the boombox is at full battery.

**Comment by steven4547466** [comment]
I haven't experienced either of the 2 issues you've mentioned with syncing or it slowing down. The pitch doesn't change if it goes low then you recharge it, but that's just something base game that would happen even if you use the normal songs.

As for the crouching thing, I just haven't found a way to disable the character controller yet.

**Comment by steven4547466** [comment]
1.3.1 is released, try this version before reopening this issue.
