### ISSUE TITLE
Music slows down

### ISSUE THREAD

**Issue by KingDomino** [steven4547466/YoutubeBoombox#8]
Occasionally the music will slow down and pitch down when playing songs. This doesn't happen every time, but it happens about 50% of the time.

**Comment by KingDomino** [comment]
I should mention this happens regardless of battery level

**Comment by steven4547466** [comment]
What version are you on?

**Comment by KingDomino** [comment]
Latest, just downloaded an hour ago

**Comment by steven4547466** [comment]
I released a new version 30 minutes ago.

**Comment by KingDomino** [comment]
we will check it out, thanks 🙏

**Comment by steven4547466** [comment]
Newest version is 1.3.1. Reopen this issue if you encounter this again

**Comment by Thunderkill** [comment]
This happened to us on 1.5.0
