### ISSUE TITLE
Some videos with special characters in them do not play.

### ISSUE THREAD

**Issue by JonkkuSa** [steven4547466/YoutubeBoombox#9]
When trying to play some songs like this: [Lagtrain](https://youtu.be/9BAEa9TtHmM?si=ay99MGWXHIbNZ19U) the mod doesn't rename the song properly.

Screenshot of console when trying to play the song mentioned earlier.
![Screenshot 2023-12-09 100004](https://github.com/steven4547466/YoutubeBoombox/assets/38564633/5a7695be-3e8c-448a-b5ef-0a9e38c788ed)

You can also visibly see that the file's name hasn't changed.
![Screenshot 2023-12-09 100146](https://github.com/steven4547466/YoutubeBoombox/assets/38564633/f3e7ecba-c164-4d38-8e52-f70ddd7ef31f)

I suspect this happens because the name of the song has certain special characters like:
  |【 】

**Comment by RatCaptain** [comment]
Yes, i have the same issue.
![Screenshot 2023-12-09 093629](https://github.com/steven4547466/YoutubeBoombox/assets/100302313/f881358e-976f-475a-b3bf-27ddb61dcf48)
![Screenshot 2023-12-09 094037](https://github.com/steven4547466/YoutubeBoombox/assets/100302313/df4a608b-e198-4e6a-a2e1-09642465f643)
😆 
And yes seams like it has problems with special characters, but only when it tries to play the music

**Comment by steven4547466** [comment]
Will be fixed in the next version

**Comment by steven4547466** [comment]
Fixed in 1.3.1
